package de.slisson.mps.globalModelListener.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.custom.BaseCustomApplicationPlugin;

public class ApplicationPlugin_CustomApplicationPlugin extends BaseCustomApplicationPlugin {
  private MyListener listener;
  public ApplicationPlugin_CustomApplicationPlugin() {
  }
  public void doInit() {
    ApplicationPlugin_CustomApplicationPlugin.this.listener = new MyListener();
    ApplicationPlugin_CustomApplicationPlugin.this.listener.start();
  }
  public void doDispose() {
    ApplicationPlugin_CustomApplicationPlugin.this.listener.stop();
  }
}
