package de.slisson.mps.globalModelListener.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.MPSModuleRepository;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.event.SPropertyChangeEvent;

public class MyListener extends GlobalSModelListener {
  public MyListener() {
    super(MPSModuleRepository.getInstance());
    // project.getRepository() should be used, but MPS still has only repository for all projects, so it makes no difference 
  }

  @Override
  public void propertyChanged(@NotNull SPropertyChangeEvent event) {
    System.out.println("Property changed from '" + event.getOldValue() + "' to '" + event.getNewValue() + "'");
  }
}
